---
- include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include: ssh.yml
  tags: ssh_config

- include: rc_files.yml
  tags: rcfiles

- include: homebrew.yml
  tags: homebrew
  when: ansible_os_family == "Darwin"
