---
- name: Load OS Variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Configure Shell
  include_tasks:
    file: shell.yml
    apply:
      tags:
        - shell
  tags: shell

- name: Configure SSH
  include_tasks:
    file: ssh.yml
    apply:
      tags:
        - ssh_config
  tags: ssh_config

- name: Setup .rc Files
  include_tasks:
    file: rc_files.yml
    apply:
      tags:
        - rcfiles
  tags: rcfiles

- name: Install homebrew packages
  include_tasks:
    file: homebrew.yml
    apply:
      tags:
        - homebrew
  tags: homebrew
  when: ansible_os_family == "Darwin"
