---
- name: Load OS Variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Configure Shell
  include_tasks: shell.yml
  tags: shell

- name: Configure SSH
  include_tasks: ssh.yml
  tags: ssh_config

- name: Setup .rc Files
  include_tasks: rc_files.yml
  tags: rcfiles

- name: Install homebrew packages
  include_tasks: homebrew.yml
  tags: homebrew
  when: ansible_os_family == "Darwin"
