---
- name: Load OS Variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Configure Shell
  import_tasks:
    file: shell.yml
  tags:
    - shell

- name: Configure SSH
  import_tasks:
    file: ssh.yml
  tags:
    - ssh_config

- name: Setup .rc Files
  import_tasks:
    file: rc_files.yml
  tags:
    - rcfiles

- name: Install homebrew packages
  import_tasks:
    file: homebrew.yml
  tags:
    - homebrew
  when: ansible_os_family == "Darwin"

- name: Install applications from Mac App Store
  import_tasks:
    file: mas.yml
  tags:
    - mas
  when: ansible_os_family == "Darwin"
