---
- include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include_tasks: shell.yml
  tags: shell

- include_tasks: ssh.yml
  tags: ssh_config

- include_tasks: rc_files.yml
  tags: rcfiles

- include_tasks: homebrew.yml
  tags: homebrew
  when: ansible_os_family == "Darwin"
