---
- name: Ensure MAS is installed.
  homebrew:
    name: mas
    state: present

- name: Get MAS account status
  command: /usr/local/bin/mas account
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  check_mode: false
  changed_when: false

- name: Sign in to MAS when email and password are provided.
  command: '/usr/local/bin/mas signin "{{ mas_email }}" "{{ mas_password }}"'
  register: mas_signin_result
  when:
    - mas_account_result.rc == 1
    - mas_email | bool
    - mas_password | bool
    - not mas_signin_dialog

- name: Sign in to MAS when email is provided, and complete password and 2FA using dialog.
  command: '/usr/local/bin/mas signin "{{ mas_email }}" "{{ mas_password }}" --dialog'
  register: mas_signin_result
  when:
    - mas_signin_dialog
    - mas_account_result.rc == 1
    - mas_email | bool

- name: List installed MAS apps.
  command: /usr/local/bin/mas list
  register: mas_list
  check_mode: false
  changed_when: false

- name: print installed MAS apps
  debug:
    msg: "{{ mas_list.stdout }}"
    verbosity: 1

- name: Ensure configured MAS apps are installed.
  command: /usr/local/bin/mas install "{{ item.id|default(item) }}"
  loop: "{{ mas_packages }}"
  loop_control:
    label: "{{ item.name }}"
  when: (item.id | default(item) | string) not in mas_list.stdout

- name: Upgrade all apps (if configured).
  command: /usr/local/bin/mas upgrade
  when: mas_upgrade_all_apps
