---

- name: Copy vim config files
  copy:
    src: vim/
    mode: 0755
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    dest: "{{ user_homes_directory }}/{{ local_username }}/.vim/"

- name: Copy vimrc
  copy:
    src: vimrc
    mode: 0755
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    dest: "{{ user_homes_directory }}/{{ local_username }}/.vimrc"

- name: Copy screenrc
  copy:
    src: screenrc
    mode: 0755
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    dest: "{{ user_homes_directory }}/{{ local_username }}/.screenrc"

- name: Create git-aware-prompt directory in user home directory
  file:
    state: directory
    path: "{{ user_homes_directory }}/{{ local_username }}/.bash/git-aware-prompt"
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    mode: 0775

- name: Copy git-aware-profile files
  copy:
    src: "bash/git-aware-prompt/{{ item }}"
    mode: 0755
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    dest: "{{ user_homes_directory }}/{{ local_username }}/.bash/git-aware-prompt/{{ item }}"
  with_items:
    - colors.sh
    - main.sh
    - prompt.sh

- name: Copy bash_profile
  copy:
    mode: 0600
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    content: "{{ bash_profile }}"
    dest: "{{ user_homes_directory }}/{{ local_username }}/.bash_profile"

- name: Check out oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ user_homes_directory }}/{{ local_username }}/.oh-my-zsh"
    version: master
    update: no

- name: Check out Powerlevel 10k Profile
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ user_homes_directory }}/{{ local_username }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: master
    update: no

- name: Copy .zshrc
  copy:
    mode: 0600
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    content: "{{ zshrc }}"
    dest: "{{ user_homes_directory }}/{{ local_username }}/.zshrc"

- name: Copy Powerlevel 10K Config
  copy:
    mode: 0600
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    content: "{{ p10krc }}"
    dest: "{{ user_homes_directory }}/{{ local_username }}/.p10k.zsh"

- name: Copy git config
  copy:
    mode: 0600
    owner: "{{ local_username }}"
    group: "{{ local_user_groupname }}"
    content: "{{ git_config }}"
    dest: "{{ user_homes_directory }}/{{ local_username }}/.gitconfig"
